on:
  push:
    branches:
      - main
      
jobs:
  checks:
    runs-on: macos-latest
    env:
      PIPENV_VENV_IN_PROJECT: enable
      
    steps:
        - name: Checkout source code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.7.6"

        # - name: Install pipenv
        #   run: |
        #     python -m pip install --upgrade pipenv wheel
            
        # - name: Install dependencies
        #   run: |
        #     pipenv install
            
        # - name: Run tests
        #   id: run_test
        #   run: |
        #     pipenv run pytest
        

  # deploy:

  #   runs-on: ubuntu-latest
  #   needs: [checks]

  #   steps:
  #     - name: Trigger AWS CodePipeline
  #       uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
  #       with:
  #         aws-region: "ap-northeast-2"
  #         aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
  #         aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
  #         pipeline-name: "aws-infra-prac"